language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
env:
  matrix:
    - DJANGO_VERSION=1.9 DATABASE_URL='sqlite://localhost/:memory:'
    - DJANGO_VERSION=1.9 DATABASE_URL='mysql://travis@127.0.0.1/django_prometheus_1'
    - DJANGO_VERSION=1.9 DATABASE_URL='postgres://postgres@127.0.0.1/postgres'

services:
  - mysql
  - postgresql

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.4
    - python: "3.3"
      env: DJANGO_VERSION=1.9
    - python: "3.4"
      env: DJANGO_VERSION=1.4
    - python: "3.5"
      env: DJANGO_VERSION=1.4
    - python: "3.5"
      env: DJANGO_VERSION=1.5
    - python: "3.5"
      env: DJANGO_VERSION=1.6
    - python: "3.5"
      env: DJANGO_VERSION=1.7

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - mysql -e 'create database django_prometheus_1;'

before_script:
  - pep8 .

script:
  - python setup.py test
  - (cd django_prometheus/tests/end2end; PYTHONPATH=../../.. python manage.py test)
